name: "Benchmark workflow"
on:
  # Push and update benchmarks when a commit is merged into master.
  push:
    branches:
      - master
  # Trigger benchmark test on this PR's commit against master.
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4.0.1
        with:
          go-version-file: 'go.mod'
      - run: go version
      - name: Build go-quarkonium
        run: scripts/travis/build.sh
      # BenchmarkUintMath - Serves as a proxy for AVM eval performance.
      # Performance degradations suggest either or both:  (1) op code
      # degradation, (2) eval degradation.  (2) suggests a broader performance
      # issue. 
      - name: Run benchmark
        run: go test ./data/transactions/logic -bench 'BenchmarkUintMath' -run=^$ | tee benchmark_output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark_output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-always: false
          save-data-file: true
          alert-threshold: '200%'
          fail-on-alert: false
          comment-on-alert: ${{ github.event_name == 'pull_request' }}