name: "codegen verification"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  codegen_verification:
    runs-on: ubuntu-latest
    services:
      converter:
        image: swaggerapi/swagger-converter@sha256:dcfd1c2537f5f271cb4ec942d08aa59ca41b9a24078040061a772afca7e548ae # v1.0.4
        ports:
          - 8080:8080
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: go-quarkonium
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.10'
      - name: Uninstall existing go installation
        run: sudo apt-get -y -q purge golang-go
      - name: Run codegen_verification.sh
        env:
          SWAGGER_CONVERTER_API: "http://localhost:8080"
        run: |
          export GOPATH="${GITHUB_WORKSPACE}/go"
          cd go-quarkonium
          scripts/travis/codegen_verification.sh
